# Zeppelin Home - GitHub Pages Configuration
title: "Zeppelin Home"
description: "Innovative floating home solutions for modern living"
baseurl: "/zeppelin-home"
url: "https://hannesmitterer.github.io"

# GitHub Pages settings
repository: hannesmitterer/zeppelin-
github_username: hannesmitterer

# Jekyll theme
theme: minima

# Navigation
header_pages:
  - docs/index.md

# SEO and social
author:
  name: "Zeppelin Home Project"
  email: "press@zeppelinhome.com"

social_links:
  - { platform: github, user_url: "https://github.com/hannesmitterer/zeppelin-" }

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Markdown settings
markdown: kramdown
highlighter: rouge

# Collections
collections:
  pages:
    output: true
    permalink: /:name/

# Exclude from processing
exclude:
  - .gitignore
  - LICENSE
  - README.md
  - vendor/
  - .bundle/